# Ansible Playbook for Subutai's Readthedocs
---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks:

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade
      
    
- hosts: rtd
  remote_user: root
  tasks:

    - name: Install extra packages
      apt: 
        name: "{{ item }}"
      with_items:
        - wget
        - xz-utils
        - build-essential
        - libsqlite3-dev
        - libreadline-dev
        - libxml2-dev
        - libxslt1-dev
        - libssl-dev
        - openssl
        - zlib1g-dev
        - libbz2-dev
        - git
        - python3
        - python3-pip
        - python3-dev
        - python3-setuptools
        - virtualenv
        - python-pip
    
    - name: Create Virtual Env Dir
      file:
          path: /srv/rtd
          state: directory

    - name: Create Virtual Env
      command: virtualenv -p /usr/bin/python3.7 --system-site-packages --always-copy /srv/rtd/rtd_env

    - name: Install RTD
      git: 
        repo: https://github.com/rtfd/readthedocs.org.git 
        dest: /srv/rtd/source
        version: 4.1.4

    - name: Install requirements from pip
      pip:
        virtualenv: /srv/rtd/rtd_env
        virtualenv_python: python3
        requirements: /srv/rtd/source/requirements/pip.txt

 #   - name: Install flup 
 #     pip:
 #       name: flup
 #       virtualenv: /srv/rtd/rtd_env    

    - name: RTD Server migrate
      django_manage:
          app_path: /srv/rtd/source
          virtualenv: /srv/rtd/rtd_env
          command: migrate

    - name: RTD generate the static assets
      django_manage:
          app_path: /srv/rtd/source
          virtualenv: /srv/rtd/rtd_env
          command: collectstatic

    - name: Create Django super user
      shell:
          . ../rtd_env/bin/activate && echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', '{{ user_email }}', '{{ user_password }}')" | python3 manage.py shell
      args:
          chdir: /srv/rtd/source

    #- name: Install uWSGI
    # pip:
    #      name: uwsgi
    #      virtualenv: /srv/rtd/rtd_env

    #- name: Configure Rtd ini file 
    #  copy:
    #      src:  uwsgi/rtd.ini
    #      dest: /srv/rtd/source/readthedocs/rtd.ini
    #      owner: root
    #      group: root


    - name: RTD Server Up 
      shell: . ../rtd_env/bin/activate && nohup python3 manage.py runserver 0.0.0.0:8000 &
      args:
          chdir: /srv/rtd/source
